config/routes.rb
Rails.application.routes.draw do
  
  get 'movies/show'
  get 'quizzes/show'

  root 'quizzes#index'

  
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	belongs_to :quiz

	def self.assign_answer_key (val1, val2, val3, val4)


		if val1 == "Y" && val2 == "Y" && val3 == "Y" && val4 == "Y"

			answer_key = 0

			# find_movie(answer_key)

		elsif val1 == "Y" && val2 == "Y" && val3 == "Y" && val4 == "N"

			answer_key = 1

		elsif val1 == "Y" && val2 == "Y" && val3 == "N" && val4 == "Y"

			answer_key = 2

		elsif val1 == "Y" && val2 == "N" && val3 == "Y" && val4 == "Y"

			answer_key = 3

		elsif val1 == "N" && val2 == "Y" && val3 == "Y" && val4 == "Y"

			answer_key = 4

		elsif val1 == "Y" && val2 == "Y" && val3 == "N" && val4 == "N"

			answer_key = 5
			
		elsif val1 == "Y" && val2 == "N" && val3 == "N" && val4 == "Y"
					
			answer_key = 6

		elsif val1 == "N" && val2 == "N" && val3 == "Y" && val4 == "Y"

			answer_key = 7

		elsif val1 == "Y" && val2 == "N" && val3 == "N" && val4 == "N"
			
			answer_key = 8

		elsif val1 == "N" && val2 == "N" && val3 == "N" && val4 == "Y"

			answer_key = 9

		elsif val1 == "Y" && val2 == "N" && val3 == "Y" && val4 == "N"

			answer_key = 10

		elsif val1 == "N" && val2 == "Y" && val3 == "N" && val4 == "Y"
			
			answer_key = 11

		elsif val1 == "N" && val2 == "Y" && val3 == "Y" && val4 == "N"
			
			answer_key = 12

		elsif val1 == "N" && val2 == "N" && val3 == "Y" && val4 == "N"
			
			answer_key = 13

		elsif val1 == "N" && val2 == "Y" && val3 == "N" && val4 == "N"
			
			answer_key = 14

		elsif val1 == "N" && val2 == "N" && val3 == "N" && val4 == "N"
			
			answer_key = 15
			
		end

	end

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_quiz
  	Quiz.find(session[:quiz_id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def show

  	value_1 = params[:value_1]
  	value_2 = params[:value_2]
  	value_3 = params[:value_3]
  	value_4 = params[:value_4]
  	quiz_id = params[:quiz_id]
		
		answer_id = Movie.assign_answer_key(value_1, value_2, value_3, value_4)

		@movie = Movie.find_by(answer_key: answer_id, quiz_id: quiz_id)

  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
	# before_action :set_quiz, only: :show

  def index
  	@quizzes = Quiz.all
  end

  def show

    @quiz = Quiz.find(params[:id])

  end

  # private

  # def set_quiz
  	
  #   # current_quiz = params[:id]
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/question_sets_controller_helper.rb
module QuestionSetsControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeMakeSense</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/show.html.erb
<p><%=@movie.title%></p>

app/views/quizzes/index.html.erb
<div class="quiz_container">

	<div class="quiz_row">

		<h1 style="text-align:center">Pick a movie! You'll be taken to a quiz where we'll make your personalized movie reccomendation</h1>

	</div>

	<div class="quiz_row">

		<% @quizzes.each do |quiz|%>

			<div class='quizzes'>

				<h3><%= link_to quiz.label, quizzes_show_path(:id => quiz.id) %></h3>

			</div>

		<% end %>

	</div>

</div>

app/views/quizzes/show.html.erb
<div class="quiz_container">

	<div class="quiz_row">
		<h1>Quiz for <%= @quiz.label %> </h1>
	</div>

	<div class="quiz_row">

		<div class="questions">

			<%= form_tag(movies_show_path, method: "get") do %>

			<h3><%= @quiz.question_1 %></h3>

				<%= radio_button_tag(:value_1, "Y") %>
				<%= label_tag(:value_1_Y, "Y") %>
				<%= radio_button_tag(:value_1, "N") %>
				<%= label_tag(:value_1_N, "N") %>

			<h3><%= @quiz.question_2 %></h3>

				<%= radio_button_tag(:value_2, "Y") %>
				<%= label_tag(:value_2_Y, "Y") %>
				<%= radio_button_tag(:value_2, "N") %>
				<%= label_tag(:value_2_N, "N") %>

			<h3><%= @quiz.question_3 %></h3>

				<%= radio_button_tag(:value_3, "Y") %>
				<%= label_tag(:value_3_Y, "Y") %>
				<%= radio_button_tag(:value_3, "N") %>
				<%= label_tag(:value_3_N, "N") %>

			<h3><%= @quiz.question_4 %></h3>

				<%= radio_button_tag(:value_4, "Y") %>
				<%= label_tag(:value_4_Y, "Y") %>
				<%= radio_button_tag(:value_4, "N") %>
				<%= label_tag(:value_4_N, "N") %>

				<%= radio_button_tag(:quiz_id, @quiz.id, checked: true) %>


				<%= submit_tag("Search") %>

			<% end %>

		</div>

	</div>

</div>